---
name: switchbot
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      switchbot_exporter:
        image: nasa9084/switchbot-exporter:latest
        ports:
          - 8080/tcp
        env:
          SWITCHBOT_OPENTOKEN: ${{ secrets.switchbot_open_token }}
          SWITCHBOT_SECRETKEY: ${{ secrets.switchbot_secret_key }}

    steps:
      - name: Sleep for a while
        run: sleep 5s
      - name: Generate page
        run: |
          mkdir -p public
          touch public/metrics

          curl -s "http://localhost:${{ job.services.switchbot_exporter.ports['8080'] }}/metrics" | tee public/metrics
          cp public/metrics public/metrics.txt

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
