---
name: switchbot
on:
  schedule:
    # At every 5th minute from 3 through 59.
    - cron: '3/5 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  push:
    runs-on: ubuntu-latest
    services:
      switchbot_exporter:
        image: nasa9084/switchbot-exporter:latest
        ports:
          - 8080/tcp
        env:
          SWITCHBOT_OPENTOKEN: ${{ secrets.switchbot_open_token }}
          SWITCHBOT_SECRETKEY: ${{ secrets.switchbot_secret_key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Push
        run: go run ./cmd/otelpush
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
          EXPORTER_PORT: ${{ job.services.switchbot_exporter.ports['8080'] }}
